#!/usr/bin/env python3
"""
Russian translation pass 2 - Translate all remaining 723 untranslated entries + fix fuzzy.
"""

import polib

PO_FILE = '/opt/infrasignal-v2/locale/ru_RU.UTF-8/LC_MESSAGES/FixMyStreet.po'

# Complete translation dictionary for ALL remaining untranslated entries
T = {
    # --- HTML / long entries ---
    '<label for="statuses">Show</label> %s reports <label for="filter_categories">about</label> %s':
        '<label for="statuses">Показать</label> %s отчётов <label for="filter_categories">о</label> %s',
    '<strong>No</strong> Let me confirm my report by email/text':
        '<strong>Нет</strong> Позвольте мне подтвердить отчёт по эл. почте/SMS',
    '<strong>No</strong> Let me confirm my update by email/text':
        '<strong>Нет</strong> Позвольте мне подтвердить обновление по эл. почте/SMS',
    '<strong>One at a time!</strong> Multiple street names in a single search can confuse us.':
        '<strong>По одной!</strong> Несколько улиц в одном запросе могут вызвать путаницу.',
    '<u>Take or choose existing photo</u>': '<u>Сделать или выбрать фото</u>',

    # --- A ---
    'A service ID (Open311 or similar).': 'ID сервиса (Open311 или аналог).',
    'Access denied': 'Доступ запрещён',
    'Access detailed statistics on reports and performance in your area \u2013 for free. Only available to council staff.':
        'Доступ к подробной статистике по отчётам и показателям в вашем районе — бесплатно. Доступно только для сотрудников.',
    'Activate two-factor authentication': 'Активировать двухфакторную аутентификацию',
    'Add another parent category': 'Добавить ещё одну родительскую категорию',
    'Add email address': 'Добавить адрес эл. почты',
    'Add extra fields': 'Добавить дополнительные поля',
    'Add field': 'Добавить поле',
    'Add fixed state': 'Добавить статус «исправлено»',
    'Add option': 'Добавить вариант',
    'Add phone number': 'Добавить номер телефона',
    'Add time period': 'Добавить период',
    'Add to shortlist': 'Добавить в избранное',
    'Add/edit problem categories': 'Добавить/редактировать категории проблем',
    'Add/edit response priorities': 'Добавить/редактировать приоритеты ответов',
    'Add/edit response templates': 'Добавить/редактировать шаблоны ответов',
    "Adding this report to your shortlist will remove it from %s\u2019s shortlist.":
        'Добавление этого отчёта в ваше избранное удалит его из избранного %s.',
    "Adding this report to your shortlist will remove it from %s's shortlist.":
        'Добавление этого отчёта в ваше избранное удалит его из избранного %s.',
    'Aerial map': 'Аэрофотокарта',
    'Alerts:': 'Оповещения:',
    'All': 'Все',
    'All categories': 'Все категории',
    'All cobrands': 'Все кобренды',
    'All languages': 'Все языки',
    'Allow anonymous reports on this category': 'Разрешить анонимные отчёты в этой категории',
    'Already been reported?': 'Уже сообщалось?',
    'Alternatively, we can hide your name on <strong>all of your reports and updates</strong> across the site:':
        'Или мы можем скрыть ваше имя во <strong>всех ваших отчётах и обновлениях</strong> на сайте:',
    'Always fetch all problems': 'Всегда получать все проблемы',
    'An email address or service ID (Open311 or similar).': 'Адрес эл. почты или ID сервиса (Open311 или аналог).',
    'An email address.': 'Адрес электронной почты.',
    'Anonymous user': 'Анонимный пользователь',
    'Another user': 'Другой пользователь',
    'Are you sure you want to cancel this upload?': 'Вы уверены, что хотите отменить загрузку?',
    'Are you sure you wish to delete this draft report?': 'Вы уверены, что хотите удалить этот черновик?',
    'Area:': 'Район:',
    'Asset ID:': 'ID объекта:',
    'Assign': 'Назначить',
    'Assign problem reports to users': 'Назначать отчёты пользователям',
    'Assign selected to role:': 'Назначить выбранным роль:',
    'Assign to': 'Назначить',
    'Assign to:': 'Назначить:',
    'Assign users to areas': 'Назначать пользователей районам',
    'Assigned categories only': 'Только назначенные категории',
    'Assigned to': 'Назначено',
    'Authorised staff users can be associated with the categories in which they operate.':
        'Авторизованные сотрудники могут быть связаны с категориями, в которых они работают.',
    'Auto Response': 'Автоответ',
    'Auto-response:': 'Автоответ:',
    'Automatically populate report subject/detail': 'Автоматически заполнять тему/детали отчёта',
    'Average time between a problem being reported and being fixed, last 100 reports.':
        'Среднее время от сообщения до исправления, последние 100 отчётов.',
    'Avoid personal information and vehicle number plates': 'Избегайте личной информации и номерных знаков автомобилей',
    'Back to all reports': 'Вернуться ко всем отчётам',
    'Background Colour': 'Цвет фона',
    'Ban user': 'Заблокировать пользователя',
    'Be polite': 'Будьте вежливы',
    'Behaviour': 'Поведение',
    'Bins, rubbish and recycling': 'Контейнеры, мусор и переработка',
    'Bulky items list': 'Список крупногабаритных предметов',
    'CSV File': 'CSV файл',
    'Categories:': 'Категории:',
    'Category and State': 'Категория и статус',
    'Change': 'Изменить',
    'Change asset': 'Изменить объект',
    'Change email address': 'Изменить адрес эл. почты',
    'Change phone number': 'Изменить номер телефона',
    'Change two-factor authentication': 'Изменить двухфакторную аутентификацию',
    'Checkboxes': 'Флажки',
    'Choose another': 'Выбрать другой',
    'Choose location, pan and zoom to adjust': 'Выберите место, перемещайте и масштабируйте для уточнения',
    'Clear offline data': 'Очистить офлайн-данные',
    'Click the link in that email to sign in.': 'Нажмите на ссылку в письме для входа.',
    'Click the map or drag the pin to adjust the location': 'Нажмите на карту или перетащите метку для уточнения места',
    'Closed to updates': 'Закрыт для обновлений',
    'Code': 'Код',
    'Codes for extra data must not contain spaces': 'Коды дополнительных данных не должны содержать пробелы',
    'Collapse map': 'Свернуть карту',
    'Config must be a JSON object literal, not array.': 'Конфигурация должна быть объектом JSON, а не массивом.',
    'Continue': 'Продолжить',
    'Convert location from Easting/Northing': 'Преобразовать координаты из Easting/Northing',
    'Create': 'Создать',
    'Create an account': 'Создать аккаунт',
    'Create message': 'Создать сообщение',
    'Create priority': 'Создать приоритет',
    'Create reports/updates as anonymous user': 'Создавать отчёты/обновления как анонимный пользователь',
    'Create reports/updates as the council': 'Создавать отчёты/обновления от имени администрации',
    "Create reports/updates on a user's behalf": 'Создавать отчёты/обновления от имени пользователя',
    'Created %d new users': 'Создано %d новых пользователей',
    'Created Body': 'Созданная организация',
    'Created By': 'Создано',
    'Credit Card': 'Кредитная карта',
    'Current password:': 'Текущий пароль:',
    'Currently grouped by %s': 'Группировка по %s',
    'Datetime picker': 'Выбор даты и времени',
    'Deactivate two-factor authentication': 'Деактивировать двухфакторную аутентификацию',
    'Default': 'По умолчанию',
    'Default to creating reports/updates as the council': 'По умолчанию создавать отчёты от имени администрации',
    'Delete theme': 'Удалить тему',
    'Describe why you are moderating this': 'Опишите причину модерации',
    'Destination': 'Назначение',
    'Detailed information is limited to %d characters.': 'Подробная информация ограничена %d символами.',
    'Details hint text': 'Подсказка для деталей',
    'Device and Site': 'Устройство и сайт',
    'Direct Debit': 'Прямое списание',
    'Disable': 'Отключить',
    'Disable form when this category is selected': 'Отключить форму при выборе этой категории',
    'Disable form when this option is selected': 'Отключить форму при выборе этого варианта',
    'Disable reopening of reports in this category': 'Запретить повторное открытие отчётов в этой категории',
    'Disable updates on reports in this category': 'Отключить обновления для отчётов в этой категории',
    'Disabled:': 'Отключено:',
    'Discard changes': 'Отменить изменения',
    'Display as': 'Отображать как',
    'Displayed label': 'Отображаемая метка',
    'Do not send email alerts on fetched comments to problem creator':
        'Не отправлять оповещения о полученных комментариях автору проблемы',
    "Don't show": 'Не показывать',
    'Done': 'Готово',
    "Don\u2019t identify or accuse other\u00a0people": 'Не называйте и не обвиняйте\u00a0других',
    "Don\u2019t include private contact details in the\u00a0description": 'Не включайте личные контактные данные в\u00a0описание',
    'Down one': 'Вниз на одну',
    'Drag photos here or <u>browse photos</u>': 'Перетащите фото сюда или <u>выберите фото</u>',
    'Draw rectangles on the picture then click Done.': 'Нарисуйте прямоугольники на изображении и нажмите Готово.',
    'Drop pin on the map to start a new report': 'Поставьте метку на карте для нового отчёта',
    'Drop-down list': 'Выпадающий список',
    'Duplicate of': 'Дубликат',
    'Duplicates': 'Дубликаты',
    'Easting/Northing:': 'Восток/Север:',
    "Edit other users' permissions": 'Редактировать разрешения других пользователей',
    'Edit report category': 'Редактировать категорию отчёта',
    'Edit report priority': 'Редактировать приоритет отчёта',
    'Edit reports': 'Редактировать отчёты',
    "Edit users' details/search for their reports": 'Редактировать данные пользователей/искать их отчёты',
    'Edit your update': 'Редактировать ваше обновление',
    'Email address (optional)': 'Адрес эл. почты (необязательно)',
    'Email me a link or text me a code to sign in': 'Отправить ссылку по почте или код по SMS для входа',
    'Email me a link to sign in': 'Отправить ссылку для входа по почте',
    'Email verified:': 'Почта подтверждена:',
    'Enable': 'Включить',
    'End Date': 'Дата окончания',
    'End time': 'Время окончания',
    'Ending in .gov.uk, or other official council domain': 'Оканчивающийся на .gov.uk или другой официальный домен',
    'Enter the road name, postcode or the area closest to the problem':
        'Введите название дороги, почтовый индекс или район рядом с проблемой',
    'Existing category': 'Существующая категория',
    "Existing users won\u2019t be modified.": 'Существующие пользователи не будут изменены.',
    "Existing users won't be modified.": 'Существующие пользователи не будут изменены.',
    'Explain what\u2019s wrong': 'Объясните, в чём проблема',
    "Explain what's wrong": 'Объясните, в чём проблема',
    'Export CSV preview (100 rows)': 'Экспорт CSV (предпросмотр 100 строк)',
    'Export as CSV': 'Экспорт в CSV',
    'External body': 'Внешняя организация',
    'External status code': 'Внешний код статуса',
    'External status code:': 'Внешний код статуса:',
    'External team': 'Внешняя команда',
    'Extra Fields': 'Дополнительные поля',
    'Extra details': 'Дополнительные детали',
    'Extra fields:': 'Дополнительные поля:',
    'Extra question shown to user': 'Дополнительный вопрос пользователю',
    'Fields': 'Поля',
    'File type not recognised. Please upload an image.': 'Тип файла не распознан. Загрузите изображение.',
    'Fill in your details manually.': 'Заполните свои данные вручную.',
    'Five most recent commented reports': 'Пять последних прокомментированных отчётов',
    'Five newest reports': 'Пять новейших отчётов',
    'FixMyStreet Android app on Google Play': 'Приложение InfraSignal для Android в Google Play',
    'FixMyStreet Conditions of Use': 'Условия использования InfraSignal',
    'FixMyStreet Platform': 'Платформа InfraSignal',
    'FixMyStreet app on the App Store': 'Приложение InfraSignal в App Store',
    'For best results include a close-up and a wide shot': 'Для лучшего результата приложите крупный план и общий вид',
    'For citizens': 'Для граждан',
    'For council staff only. Access detailed statistics on reports and performance in your area.':
        'Только для сотрудников. Доступ к подробной статистике по отчётам и показателям в вашем районе.',
    'For developers': 'Для разработчиков',
    'Forgot password': 'Забыли пароль',
    'Frontend staff access only to users assigned to this category':
        'Доступ фронтенда только для пользователей, назначенных этой категории',
    'General Enquiry': 'Общий вопрос',
    'Generate token': 'Создать токен',
    'Grant access to the admin': 'Предоставить доступ к админпанели',
    'Great work. Now spread the word!': 'Отличная работа. Расскажите друзьям!',
    'Group by %s': 'Группировать по %s',
    'Group by:': 'Группировать по:',
    'Heatmap': 'Тепловая карта',
    'Here are some other nearby reports:': 'Вот другие отчёты поблизости:',
    'Hidden data in reporting form': 'Скрытые данные в форме',
    'Hide all reports and updates': 'Скрыть все отчёты и обновления',
    'Hide entire report': 'Скрыть весь отчёт',
    'Hide my name': 'Скрыть моё имя',
    'Hide my name everywhere': 'Скрыть моё имя везде',
    'Hide my name in this update': 'Скрыть моё имя в этом обновлении',
    'Hide my name on this report': 'Скрыть моё имя в этом отчёте',
    'Hide reports made in this category': 'Скрыть отчёты в этой категории',
    'Hide update completely?': 'Полностью скрыть обновление?',
    'Hide your name?': 'Скрыть ваше имя?',
    'I am from a council and I have a question for the FixMyStreet team':
        'Я из администрации и у меня вопрос к команде InfraSignal',
    'I have feedback about the site': 'У меня есть отзыв о сайте',
    'I need help using the site': 'Мне нужна помощь в использовании сайта',
    'I want to make a new report about a street problem': 'Я хочу сообщить о проблеме на улице',
    'Import users': 'Импорт пользователей',
    'In wards': 'В районах',
    'Information for citizens': 'Информация для граждан',
    'Instruct contractors to fix problems': 'Давать подрядчикам указания по устранению проблем',
    'Internal data set by Open311': 'Внутренние данные Open311',
    'Internal key': 'Внутренний ключ',
    'Invalid location. New location must be covered by the same council.':
        'Недопустимое расположение. Новое место должно быть в зоне той же администрации.',
    'Label': 'Метка',
    'Language': 'Язык',
    'Languages': 'Языки',
    'Last failure:': 'Последняя ошибка:',
    'Last update': 'Последнее обновление',
    'Latitude/Longitude:': 'Широта/Долгота:',
    'Learn more': 'Узнать больше',
    'Least recently updated': 'Давно не обновлявшиеся',
    'Loading reports\u2026': 'Загрузка отчётов…',
    'Log in here.': 'Войдите здесь.',
    'Log in with Facebook': 'Войти через Facebook',
    'Log in with Twitter': 'Войти через Twitter',
    'Log in with email': 'Войти по эл. почте',
    'Log in with email/text': 'Войти по эл. почте/SMS',
    'Log out of all sessions': 'Выйти из всех сессий',
    'Login with %s': 'Войти через %s',
    'Look up': 'Найти',
    'Make anonymous on all reports and updates': 'Сделать анонимным во всех отчётах',
    'Manage shortlist': 'Управление избранным',
    'Manifest Theme': 'Тема манифеста',
    'Manual order': 'Ручной порядок',
    'Markup problem details': 'Разметка деталей проблемы',
    'Message to show when form is disabled (HTML permitted)': 'Сообщение при отключённой форме (HTML разрешён)',
    'Missing bodies:': 'Отсутствующие организации:',
    'Moderate report details': 'Модерировать детали отчёта',
    'Moderate this report': 'Модерировать этот отчёт',
    'Moderate this update': 'Модерировать это обновление',
    'Moderated by %s at %s': 'Модерировано %s в %s',
    'Moderation history': 'История модерации',
    'Most popular categories in %s': 'Самые популярные категории в %s',
    'Multiple Groups': 'Несколько групп',
    'Names are limited to %d characters in length.': 'Имена ограничены %d символами.',
    'Navigate to this problem': 'Перейти к этой проблеме',
    'Nearest calculated address:': 'Ближайший рассчитанный адрес:',
    'Nearly done!': 'Почти готово!',
    'Nearly done! Now check your phone\u2026': 'Почти готово! Проверьте ваш телефон…',
    'Nearly done! Now check your phone&hellip;': 'Почти готово! Проверьте ваш телефон&hellip;',
    'New field': 'Новое поле',
    'New problems for %s': 'Новые проблемы для %s',
    'New problems for <a href="%s">%s</a>': 'Новые проблемы для <a href="%s">%s</a>',
    'New problems for <a href="%s">%s</a> ward in <a href="%s">%s</a>':
        'Новые проблемы для района <a href="%s">%s</a> в <a href="%s">%s</a>',
    'New problems for area id <a href="%s">%s</a>': 'Новые проблемы для района <a href="%s">%s</a>',
    'New problems for ward id %s in body id %s': 'Новые проблемы для района %s в организации %s',
    'New problems near <a href="%s">%s,%s</a>': 'Новые проблемы рядом с <a href="%s">%s,%s</a>',
    'New updates on report <a href="%s">%s</a>': 'Новые обновления для отчёта <a href="%s">%s</a>',
    'Next:': 'Далее:',
    'No Group': 'Без группы',
    'No account?': 'Нет аккаунта?',
    'No personal details will be stored, and you will not receive updates about this report.':
        'Личные данные не будут сохранены, и вы не будете получать обновления по этому отчёту.',
    'No reports to show on map, here are some nearby:': 'Нет отчётов для показа на карте, вот ближайшие:',
    'Not a valid JSON string: %s': 'Недопустимая строка JSON: %s',
    'Not from yourself/backend': 'Не от себя/бэкенда',
    'Notice shown to user': 'Уведомление для пользователя',
    'Notice text': 'Текст уведомления',
    'Number of problems reported in each category, in the last 7 days.':
        'Количество проблем по категориям за последние 7 дней.',
    'Offline data cleared': 'Офлайн-данные очищены',
    'Offline update data saved': 'Офлайн-обновление сохранено',
    'On behalf of %s': 'От имени %s',
    'Only staff users will be able to add reports in this category.':
        'Только сотрудники смогут добавлять отчёты в этой категории.',
    'Only the original reporter may leave updates.': 'Только автор отчёта может оставлять обновления.',
    'Open311 API Key': 'API-ключ Open311',
    'Open311 Jurisdiction': 'Юрисдикция Open311',
    'Options': 'Параметры',
    'Or <a href="/">search for a different location</a>': 'Или <a href="/">искать другое место</a>',
    'Or sign in with password to prefill this information.': 'Или войдите с паролем для автозаполнения.',
    'Or specify a different radius distance:': 'Или укажите другой радиус:',
    'Or subscribe by RSS': 'Или подписаться по RSS',
    'Out of hours': 'Вне рабочего времени',
    'Overall average': 'Среднее общее',
    'Parent categories': 'Родительские категории',
    'Password change cancelled.': 'Смена пароля отменена.',
    'Password expired': 'Пароль устарел',
    'Perfect for civic groups, clubs, and schools.': 'Идеально для общественных групп, клубов и школ.',
    'Permissions:': 'Разрешения:',
    'Permit blank updates': 'Разрешить пустые обновления',
    'Phone Reporter:': 'Телефон автора:',
    'Phone numbers are limited to %s characters in length.': 'Номера телефонов ограничены %s символами.',
    'Phone verified:': 'Телефон подтверждён:',
    'Photo added to this report in this moderation update': 'Фото добавлено к отчёту в этом модерационном обновлении',
    'Photo deleted from this report in this moderation update': 'Фото удалено из отчёта в этом модерационном обновлении',
    'Photo upload failed.': 'Загрузка фото не удалась.',
    'Photos/Documents': 'Фото/Документы',
    'Pick your council': 'Выберите вашу администрацию',
    'Pick your ward': 'Выберите ваш район',
    'Pin map': 'Карта с метками',
    'Please check your phone number is correct': 'Пожалуйста, проверьте правильность номера телефона',
    'Please choose a less commonly-used password': 'Пожалуйста, выберите менее распространённый пароль',
    'Please enter a mobile number': 'Пожалуйста, введите номер мобильного',
    'Please enter a name': 'Пожалуйста, введите имя',
    'Please enter a name for this body': 'Пожалуйста, введите название организации',
    'Please enter a valid email or phone number': 'Пожалуйста, введите действительный адрес эл. почты или телефон',
    'Please enter your full name.': 'Пожалуйста, введите ваше полное имя.',
    'Please make sure you are not including an email address': 'Убедитесь, что вы не указываете адрес эл. почты',
    'Please make sure your password is at least %d characters long': 'Пароль должен содержать не менее %d символов',
    'Please note your report has <strong>not yet been sent</strong>.':
        'Обратите внимание: ваш отчёт <strong>ещё не отправлен</strong>.',
    'Please note your update has <strong>not yet been posted</strong>.':
        'Обратите внимание: ваше обновление <strong>ещё не отправлено</strong>.',
    'Please pick your update preference': 'Выберите предпочтительный способ обновлений',
    'Please provide a duplicate ID or public update for this report.':
        'Укажите ID дубликата или публичное обновление для этого отчёта.',
    'Please provide a public update for this report.': 'Пожалуйста, предоставьте публичное обновление для этого отчёта.',
    'Please upload an image only': 'Загрузите только изображение',
    'Please verify at least one of email/phone': 'Подтвердите хотя бы один: эл. почту или телефон',
    'Postcode': 'Почтовый индекс',
    'Postcode or street name and area': 'Почтовый индекс или улица и район',
    'Prefer this contact if multiple bodies have the same contact':
        'Предпочитать этот контакт, если несколько организаций имеют одинаковый',
    'Press': 'Нажмите',
    'Press space again to adjust the location': 'Нажмите пробел ещё раз для уточнения места',
    'Private only': 'Только приватные',
    'Problem %s added to shortlist': 'Проблема %s добавлена в избранное',
    'Problem %s created': 'Проблема %s создана',
    'Problem %s created on behalf of %s': 'Проблема %s создана от имени %s',
    'Problem %s removed from shortlist': 'Проблема %s удалена из избранного',
    'Problems in an area': 'Проблемы в районе',
    'Problems within %.1fkm of %s': 'Проблемы в радиусе %.1f км от %s',
    'Processed': 'Обработано',
    'Promotional material': 'Рекламные материалы',
    'Protect from Open311 changes': 'Защитить от изменений Open311',
    'Protect this category from being re-named': 'Защитить эту категорию от переименования',
    "Protect this category's name and group(s) from Open311 changes":
        'Защитить имя и группу(ы) этой категории от изменений Open311',
    'Provide update as': 'Предоставить обновление от имени',
    'Public details': 'Публичные данные',
    'Public update:': 'Публичное обновление:',
    'Question text': 'Текст вопроса',
    'Re-centre map': 'Перецентрировать карту',
    'Read less': 'Свернуть',
    'Read more': 'Подробнее',
    'Reason:': 'Причина:',
    'Receive a text when updates are left on this problem.': 'Получать SMS при обновлениях этой проблемы.',
    'Receive local alert notifications by': 'Получать местные оповещения через',
    'Receive update notifications by': 'Получать уведомления об обновлениях через',
    'Recently updated': 'Недавно обновлённые',
    'Redact': 'Скрыть данные',
    'Reject report': 'Отклонить отчёт',
    'Remove account details': 'Удалить данные аккаунта',
    'Remove field': 'Удалить поле',
    'Remove from shortlist': 'Удалить из избранного',
    'Remove from site': 'Удалить с сайта',
    'Remove option': 'Удалить вариант',
    'Remove staff permissions': 'Удалить права сотрудника',
    'Remove time period': 'Удалить период',
    'Replace token': 'Заменить токен',
    'Report ID:': 'ID отчёта:',
    'Report anonymously': 'Сообщить анонимно',
    'Report another problem here': 'Сообщить о другой проблеме здесь',
    'Report as': 'Отчёт от имени',
    'Report details': 'Детали отчёта',
    'Report state:': 'Статус отчёта:',
    'Report, view, and discuss local street-related problems.': 'Сообщайте, просматривайте и обсуждайте проблемы на улицах.',
    'Reports are currently not being sent to %s.': 'Отчёты в настоящее время не отправляются в %s.',
    'Reports saved offline.': 'Отчёты сохранены офлайн.',
    'Reports waiting to be sent': 'Отчёты, ожидающие отправки',
    'Reports with photos in them tend to get fixed more quickly': 'Отчёты с фотографиями обычно исправляются быстрее',
    'Reposition if needed, then hit Continue': 'Переместите при необходимости, затем нажмите Продолжить',
    'Request access': 'Запросить доступ',
    'Require a phone number to be provided': 'Требовать указание номера телефона',
    'Reset': 'Сбросить',
    'Response Priorities': 'Приоритеты ответов',
    'Response Priority for %s': 'Приоритет ответа для %s',
    'Response Template for %s': 'Шаблон ответа для %s',
    'Response Templates': 'Шаблоны ответов',
    'Restore photo': 'Восстановить фото',
    'Revert to original': 'Вернуть к исходному',
    'Revert to original text': 'Вернуть исходный текст',
    'Revert to original title': 'Вернуть исходный заголовок',
    'Road map': 'Дорожная карта',
    'Role:': 'Роль:',
    'Save + close as duplicate': 'Сохранить и закрыть как дубликат',
    'Save draft': 'Сохранить черновик',
    'Save new fields': 'Сохранить новые поля',
    'Save to this device for offline use': 'Сохранить на устройство для офлайн-использования',
    'Save with a public update': 'Сохранить с публичным обновлением',
    'Saving reports offline': 'Сохранение отчётов офлайн',
    'Search for location of email alert or RSS feed': 'Поиск места для оповещений или RSS-канала',
    'Searching by postcode?': 'Ищете по почтовому индексу?',
    'Searching by street name?': 'Ищете по названию улицы?',
    'Security': 'Безопасность',
    'See our privacy policy': 'Наша политика конфиденциальности',
    'See user detail for reports created as the council': 'Смотреть данные пользователя для отчётов от администрации',
    'Select if this is the default priority': 'Выберите, если это приоритет по умолчанию',
    'Select multiple divisions?': 'Выбрать несколько подразделений?',
    'Select multiple wards to view only reports within those wards.':
        'Выберите несколько районов для просмотра только их отчётов.',
    'Select multiple wards?': 'Выбрать несколько районов?',
    'Select:': 'Выбрать:',
    'Send Fail Count:': 'Счётчик ошибок отправки:',
    'Send a message to FixMyStreet\u2019s technical support team':
        'Отправить сообщение в службу технической поддержки InfraSignal',
    "Send a message to FixMyStreet's technical support team":
        'Отправить сообщение в службу технической поддержки InfraSignal',
    'Send extended Open311 statuses with service request updates':
        'Отправлять расширенные статусы Open311 с обновлениями запросов',
    'Send fail count:': 'Счётчик ошибок отправки:',
    'Send fail reason:': 'Причина ошибки отправки:',
    'Send login email': 'Отправить письмо для входа',
    'Set password': 'Установить пароль',
    'Set to my current location': 'Установить на моё текущее местоположение',
    'Shortlist all visible': 'Добавить все видимые в избранное',
    'Shortlisted': 'В избранном',
    'Shortlisted by %s': 'В избранном у %s',
    'Show all updates': 'Показать все обновления',
    'Show location information page': 'Показать страницу информации о месте',
    'Show name publicly?': 'Показывать имя публично?',
    'Show older': 'Показать старые',
    'Show older reports': 'Показать старые отчёты',
    'Show photo': 'Показать фото',
    'Show reporter&rsquo;s name': 'Показать имя автора',
    'Skip map': 'Пропустить карту',
    'Skip to main content': 'Перейти к основному содержанию',
    'Skipped': 'Пропущено',
    'Someone has moderated this report since you started.': 'Кто-то модерировал этот отчёт с момента вашего начала.',
    'Sorry! You\u2019ve hit the limit of images that can be attached to one report.':
        'Вы достигли лимита изображений для одного отчёта.',
    "Sorry! You've hit the limit of images that can be attached to one report.":
        'Вы достигли лимита изображений для одного отчёта.',
    'Sorry, that wasn&rsquo;t the correct code': 'Извините, это неверный код',
    'Sorry, we could not log you in. Please fill in the form below.':
        'Не удалось войти. Пожалуйста, заполните форму ниже.',
    "Sorry, we couldn\u2019t save your file(s), please try again.":
        'Не удалось сохранить файл(ы), попробуйте снова.',
    "Sorry, we couldn't save your file(s), please try again.":
        'Не удалось сохранить файл(ы), попробуйте снова.',
    "Sorry, you don\u2019t have permission to do that.": 'У вас нет разрешения на это действие.',
    "Sorry, you don't have permission to do that.": 'У вас нет разрешения на это действие.',
    'Specify a radius in kilometres': 'Укажите радиус в километрах',
    'Staff only': 'Только для сотрудников',
    'Staff users have permission to log in to the admin.': 'Сотрудники имеют право входа в админпанель.',
    'Staff:': 'Сотрудники:',
    'Staging site': 'Тестовый сайт',
    'Start Date': 'Дата начала',
    'Start a new offline report': 'Создать новый офлайн-отчёт',
    'State and external status code cannot be used simultaneously.':
        'Статус и внешний код статуса нельзя использовать одновременно.',
    'State changed to:': 'Статус изменён на:',
    'States': 'Статусы',
    'Still open, via questionnaire': 'Всё ещё открыт (по анкете)',
    'Subscribe by email': 'Подписаться по эл. почте',
    'Subscribed:': 'Подписан:',
    'Summarise the problem': 'Опишите проблему кратко',
    'Summarise your changes': 'Опишите ваши изменения',
    'Summary hint text': 'Подсказка для описания',
    'Summary statistics': 'Сводная статистика',
    'Superuser:': 'Суперпользователь:',
    'Tell us about you': 'Расскажите о себе',
    'Ten least recently updated open reports': 'Десять давно не обновлявшихся открытых отчётов',
    'Text alert created': 'SMS-оповещение создано',
    'Text alert deleted': 'SMS-оповещение удалено',
    'Text field': 'Текстовое поле',
    'Text for email alert:': 'Текст для оповещения:',
    'Textarea': 'Текстовая область',
    'Thank you for your enquiry': 'Спасибо за ваш запрос',
    'That user has been logged out.': 'Пользователь отключён от системы.',
    "That user has been made anonymous on all reports and updates.":
        'Пользователь стал анонимным во всех отчётах и обновлениях.',
    "That user\u2019s personal details have been removed.": 'Личные данные пользователя удалены.',
    "That user's personal details have been removed.": 'Личные данные пользователя удалены.',
    "That user\u2019s reports and updates have been hidden.": 'Отчёты и обновления пользователя скрыты.',
    "That user's reports and updates have been hidden.": 'Отчёты и обновления пользователя скрыты.',
    'The contact has been confirmed as correct.': 'Контакт подтверждён как правильный.',
    'The reporting message will be shown on reporting pages.': 'Сообщение будет показано на страницах отчётности.',
    'The uploaded CSV file must contain a header row, and records can have the following fields:':
        'Загруженный CSV-файл должен содержать строку заголовков. Записи могут содержать следующие поля:',
    'The user has been sent a login email': 'Пользователю отправлено письмо для входа',
    'Theme': 'Тема',
    'Theme Colour': 'Цвет темы',
    'Themes': 'Темы',
    'There are similar problems nearby that we\u2019re already aware of, is one of them yours?':
        'Рядом есть похожие проблемы, о которых мы уже знаем. Одна из них ваша?',
    "There are similar problems nearby that we're already aware of, is one of them yours?":
        'Рядом есть похожие проблемы, о которых мы уже знаем. Одна из них ваша?',
    'There is already a template with that title.': 'Шаблон с таким названием уже существует.',
    'There is already an auto-response template for this category/state.':
        'Шаблон автоответа для этой категории/статуса уже существует.',
    'There must be template text if there is alternative email text.':
        'Текст шаблона обязателен при наличии альтернативного текста письма.',
    'There was a problem with your login information.': 'Проблема с вашими данными для входа.',
    'This council no longer exists.': 'Эта администрация больше не существует.',
    'This is the problem': 'Это проблема',
    'This problem is still ongoing': 'Эта проблема всё ещё актуальна',
    'This report': 'Этот отчёт',
    'This report is now closed to updates from the public.':
        'Этот отчёт больше не принимает обновления от пользователей.',
    'This site message will be shown on the homepage.': 'Это сообщение будет показано на главной странице.',
    'Tips for perfect photos': 'Советы для идеальных фото',
    'To provide an update, please <a href="%s">sign in</a>.':
        'Чтобы оставить обновление, пожалуйста, <a href="%s">войдите</a>.',
    'Token': 'Токен',
    'Too many login attempts. Please wait %d seconds before trying again':
        'Слишком много попыток входа. Подождите %d секунд перед повторной попыткой',
    'Top 5 most used categories': 'Топ-5 популярных категорий',
    'Top 5 responsive councils': 'Топ-5 отзывчивых администраций',
    'Topic:': 'Тема:',
    'Translation': 'Перевод',
    'Translations': 'Переводы',
    'Two-factor authentication': 'Двухфакторная аутентификация',
    'Two-factor authentication has been activated': 'Двухфакторная аутентификация активирована',
    'Two-factor authentication has been deactivated': 'Двухфакторная аутентификация деактивирована',
    'Unban': 'Разблокировать',
    'Undo last': 'Отменить последнее',
    'Unit type:': 'Тип единицы:',
    'Unknown update ID': 'Неизвестный ID обновления',
    'Unshortlisted': 'Удалено из избранного',
    'Up one': 'Вверх на одну',
    'Update %s created for problem %d': 'Обновление %s создано для проблемы %d',
    'Update has been marked to be skipped from sending.': 'Обновление отмечено для пропуска отправки.',
    'Update message': 'Сообщение обновления',
    'Updated by <strong>%s</strong> (%s) at %s': 'Обновлено <strong>%s</strong> (%s) в %s',
    'Updated by <strong>%s</strong> at %s': 'Обновлено <strong>%s</strong> в %s',
    'Usage notes': 'Примечания по использованию',
    'Use Open311 problem fetching': 'Использовать получение проблем Open311',
    'Use Open311 update-sending extension': 'Использовать расширение отправки обновлений Open311',
    'Use my current location': 'Использовать моё текущее местоположение',
    'User ID to attribute fetched comments to': 'ID пользователя для привязки полученных комментариев',
    'User Import': 'Импорт пользователей',
    'User added to abuse list': 'Пользователь добавлен в список нарушителей',
    'User already exists': 'Пользователь уже существует',
    'User already in abuse list': 'Пользователь уже в списке нарушителей',
    'User in abuse table': 'Пользователь в таблице нарушителей',
    "User's alerts": 'Оповещения пользователя',
    'User:': 'Пользователь:',
    'Verify': 'Подтвердить',
    'Verify email address': 'Подтвердить адрес эл. почты',
    'Verify phone number': 'Подтвердить номер телефона',
    'View divisions': 'Просмотреть подразделения',
    'View wards': 'Просмотреть районы',
    'View/Mark private reports': 'Просмотр/Пометка приватных отчётов',
    'Ward:': 'Район:',
    'WasteWorks Configuration for %s': 'Конфигурация WasteWorks для %s',
    'WasteWorks config': 'Конфигурация WasteWorks',
    'We currently send all reports to the email addresses below.':
        'В настоящее время мы отправляем все отчёты на указанные ниже адреса.',
    'We found more than one match for that location.': 'Найдено несколько совпадений для этого места.',
    'We found more than one match for that problem reference:': 'Найдено несколько совпадений для этой ссылки на проблему:',
    'We have sent a confirmation code to your phone. Please enter it below:':
        'Мы отправили код подтверждения на ваш телефон. Введите его ниже:',
    'We need your email address, please give it below.': 'Нам нужен ваш адрес эл. почты, укажите его ниже.',
    'We show up to ten matches, please try a different search if yours is not here.':
        'Показано до десяти совпадений. Попробуйте другой запрос, если вашего нет в списке.',
    'Website': 'Вебсайт',
    'What would you like to report?': 'О чём вы хотите сообщить?',
    'Which problems do you want alerts about?': 'О каких проблемах вы хотите получать оповещения?',
    'Which report is it a duplicate of?': 'Дубликатом какого отчёта он является?',
    'Would you like us to notify you when this problem is updated or fixed?':
        'Хотите, чтобы мы уведомили вас об обновлении или исправлении этой проблемы?',
    'You are currently offline': 'Вы сейчас офлайн',
    'You are not sure of the origin or validity of the contact.':
        'Вы не уверены в происхождении или действительности контакта.',
    'You are offline': 'Вы офлайн',
    'You can <a href="%s">make a new report in the same location</a>.':
        'Вы можете <a href="%s">создать новый отчёт в том же месте</a>.',
    'You can add an optional photo': 'Вы можете добавить фото (необязательно)',
    'You can move around with your keyboard': 'Вы можете перемещаться с помощью клавиатуры',
    'You can only contact the team behind FixMyStreet using our contact form':
        'Связаться с командой InfraSignal можно только через форму обратной связи',
    'You cannot rename a category to an existing category': 'Нельзя переименовать категорию в существующую',
    'You have successfully added your phone number.': 'Вы успешно добавили номер телефона.',
    'You have successfully confirmed your phone number.': 'Вы успешно подтвердили номер телефона.',
    'You have successfully removed your phone number.': 'Вы успешно удалили номер телефона.',
    'You have successfully verified your phone number.': 'Вы успешно подтвердили номер телефона.',
    'You haven&rsquo;t shortlisted any reports yet.': 'Вы ещё не добавили отчёты в избранное.',
    'Your account requires two-factor authentication to be set up.':
        'Для вашего аккаунта требуется настройка двухфакторной аутентификации.',
    'Your email or mobile': 'Ваша эл. почта или мобильный',
    'Your name has already been sent to %s, but we can hide it on this page:':
        'Ваше имя уже отправлено в %s, но мы можем скрыть его на этой странице:',
    'Your name has been hidden from all your reports and updates.':
        'Ваше имя скрыто во всех ваших отчётах и обновлениях.',
    'Your name has been hidden.': 'Ваше имя скрыто.',
    'Your offline reports': 'Ваши офлайн-отчёты',
    'Your password should include %d or more characters.': 'Ваш пароль должен содержать %d или более символов.',
    'Your report': 'Ваш отчёт',
    'Your shortlist': 'Ваше избранное',
    'Your token has been generated': 'Ваш токен создан',
    'Your update': 'Ваше обновление',
    'Your update has been saved offline for submission when back online.':
        'Ваше обновление сохранено офлайн для отправки при подключении.',
    'Your verification code is %s': 'Ваш код подтверждения: %s',
    'Yourself': 'Вы сами',
    'admin': 'админ',
    'all': 'все',
    'an administrator': 'администратор',
    'and a defect raised': 'и создан дефект',
    'disabled': 'отключено',
    'government-internal': 'внутреннее государственное',
    'left': 'влево',
    'minus': 'минус',
    'none': 'нет',
    "not the council\u2019s responsibility": 'не в ответственности администрации',
    "not the council's responsibility": 'не в ответственности администрации',
    'optional': 'необязательно',
    'or <a href="%s">create an account</a>': 'или <a href="%s">создать аккаунт</a>',
    'or <a href="%s">sign in</a>': 'или <a href="%s">войти</a>',
    'please <a href="%s">contact us</a> if we did not recognise your email':
        'пожалуйста, <a href="%s">свяжитесь с нами</a>, если мы не распознали ваш адрес',
    'plus': 'плюс',
    'right': 'вправо',
    'show': 'показать',
    'space': 'пробел',
    'this location': 'это место',
    'unassigned': 'не назначено',
    'update': 'обновление',
    'updates': 'обновления',
    'user not in abuse list': 'пользователь не в списке нарушителей',
    'user removed from abuse list': 'пользователь удалён из списка нарушителей',
    '\U0001f5d1': '\U0001f5d1',
    'Say how long the issue\u2019s been\u00a0present': 'Укажите, как давно существует\u00a0проблема',
    "Say how long the issue's been\u00a0present": 'Укажите, как давно существует\u00a0проблема',
    "Continue \u2013 report a new problem": 'Продолжить — сообщить о новой проблеме',
    "Continue – report a new problem": 'Продолжить — сообщить о новой проблеме',
    'Sending a confirmation text failed: "%s"': 'Отправка подтверждения не удалась: «%s»',
    'Your report (%d) has had an update; to view: %s\\n\\nTo stop: %s':
        'Ваш отчёт (%d) обновлён; просмотр: %s\\n\\nОтписка: %s',
    'You have <a id="oFN" href=""><span>%s</span> saved to submit</a>.':
        'У вас <a id="oFN" href="">сохранено <span>%s</span> для отправки</a>.',
    'Please <a href="#%s">check their changes</a> and resolve any differences.':
        'Пожалуйста, <a href="#%s">проверьте их изменения</a> и устраните различия.',
    'Information: Filters in use. The current view is customized based on selected filters.':
        'Информация: Используются фильтры. Текущий вид настроен на основе выбранных фильтров.',
    "Private \u2013 this will mean the report cannot be viewed publicly":
        'Приватный — отчёт не будет доступен публично',
    "Private – this will mean the report cannot be viewed publicly":
        'Приватный — отчёт не будет доступен публично',
    "Confirm by email instead, providing a new password at that point. When you confirm, your password will be updated.":
        'Подтвердить по эл. почте, указав новый пароль. При подтверждении пароль будет обновлён.',
    "Share your report on Twitter and Facebook, and let your friends join the conversation.":
        'Поделитесь отчётом в Twitter и Facebook, пусть друзья присоединятся к обсуждению.',
    "You know how to get things fixed - now make sure your friends do too.":
        'Вы знаете, как решить проблему — расскажите друзьям.',
    'Shortlist all visible': 'Добавить все видимые в избранное',
    "e.g. \u201810 inch pothole on Example St, near post box\u2019":
        'напр. «Яма 25 см на ул. Примерная, у почтового ящика»',
    "e.g. '10 inch pothole on Example St, near post box'":
        'напр. «Яма 25 см на ул. Примерная, у почтового ящика»',
    "e.g. \u2018This pothole has been here for two months and\u2026\u2019":
        'напр. «Эта яма здесь уже два месяца и…»',
    "e.g. 'This pothole has been here for two months and…'":
        'напр. «Эта яма здесь уже два месяца и…»',
    "report": 'отчёт',
}

# Plurals - Russian has 3 forms: nplurals=3
# Form 0: 1 (singular), Form 1: 2-4, Form 2: 5+ / 0
PLURALS = {
    '%d address': ('%d адрес', '%d адреса', '%d адресов'),
    '%d item requested for collection.': ('%d предмет запрошен для сбора.', '%d предмета запрошены для сбора.', '%d предметов запрошены для сбора.'),
    '%d month': ('%d месяц', '%d месяца', '%d месяцев'),
    '%d photo': ('%d фото', '%d фото', '%d фото'),
    '%d year': ('%d год', '%d года', '%d лет'),
    '%s day': ('%s день', '%s дня', '%s дней'),
    '%s problem marked as fixed': ('%s проблема отмечена как исправленная', '%s проблемы отмечены как исправленные', '%s проблем отмечено как исправленные'),
    '%s problem reported': ('%s проблема сообщена', '%s проблемы сообщены', '%s проблем сообщено'),
    '%s report': ('%s отчёт', '%s отчёта', '%s отчётов'),
    '%s update on problems': ('%s обновление проблем', '%s обновления проблем', '%s обновлений проблем'),
    '140L bin': ('контейнер 140л', 'контейнера 140л', 'контейнеров 140л'),
    '240L bin': ('контейнер 240л', 'контейнера 240л', 'контейнеров 240л'),
    'Please supply %s photo': ('Пожалуйста, приложите %s фото', 'Пожалуйста, приложите %s фото', 'Пожалуйста, приложите %s фото'),
    'Reported %d day ago': ('Сообщено %d день назад', 'Сообщено %d дня назад', 'Сообщено %d дней назад'),
    'bin': ('контейнер', 'контейнера', 'контейнеров'),
    'last updated %d day ago': ('обновлено %d день назад', 'обновлено %d дня назад', 'обновлено %d дней назад'),
    'month': ('месяц', 'месяца', 'месяцев'),
    'report': ('отчёт', 'отчёта', 'отчётов'),
    'roll': ('рулон', 'рулона', 'рулонов'),
    'you can add up to %d more item': ('вы можете добавить ещё %d предмет', 'вы можете добавить ещё %d предмета', 'вы можете добавить ещё %d предметов'),
    '<big>%s</big> completed in past month': ('<big>%s</big> выполнено за прошедший месяц', '<big>%s</big> выполнено за прошедший месяц', '<big>%s</big> выполнено за прошедший месяц'),
}

def main():
    po = polib.pofile(PO_FILE)
    translated_count = 0
    plural_count = 0
    fuzzy_fixed = 0
    skipped = []

    # Fix remaining fuzzy
    for entry in list(po.fuzzy_entries()):
        if entry.msgid in T:
            entry.msgstr = T[entry.msgid]
            if 'fuzzy' in entry.flags:
                entry.flags.remove('fuzzy')
            fuzzy_fixed += 1
        elif entry.msgid in PLURALS:
            forms = PLURALS[entry.msgid]
            entry.msgstr_plural = {0: forms[0], 1: forms[1], 2: forms[2]}
            if 'fuzzy' in entry.flags:
                entry.flags.remove('fuzzy')
            fuzzy_fixed += 1

    # Translate untranslated
    for entry in list(po.untranslated_entries()):
        if entry.msgid_plural and entry.msgid in PLURALS:
            forms = PLURALS[entry.msgid]
            entry.msgstr_plural = {0: forms[0], 1: forms[1], 2: forms[2]}
            plural_count += 1
        elif entry.msgid in T:
            entry.msgstr = T[entry.msgid]
            translated_count += 1
        else:
            skipped.append(entry.msgid[:100])

    po.save()
    
    # Re-check
    po2 = polib.pofile(PO_FILE)
    print(f"Pass 2 results:")
    print(f"  Translated: {translated_count}")
    print(f"  Plurals: {plural_count}")
    print(f"  Fuzzy fixed: {fuzzy_fixed}")
    print(f"  Skipped: {len(skipped)}")
    print(f"\nFinal stats:")
    print(f"  Total: {len(po2)}")
    print(f"  Translated: {len(po2.translated_entries())}")
    print(f"  Fuzzy: {len(po2.fuzzy_entries())}")
    print(f"  Untranslated: {len(po2.untranslated_entries())}")

    if skipped:
        print(f"\nRemaining untranslated ({len(skipped)}):")
        for i, s in enumerate(skipped[:50]):
            print(f"  {i+1}. {s!r}")

if __name__ == '__main__':
    main()
